### ISSUE TITLE
win+php5.5能用吗？是不是还要另外安装IDE才能运行？

### ISSUE THREAD

**Issue by lweo** [zhqagp/MillionHero#2]
小白求指导：）

**Comment by zhqagp** [comment]
有PHP环境即可

**Comment by lweo** [comment]
@zhqagp 怎么运行？是在地址栏输入localhost/.../hero.php? 试了不行
windows用什么运行php hero.php?  cmd窗口不行
已将wamp启动，php环境应该满足了吧
